[[news]]
date = "2024-09"
content = "我刚刚从东北师范大学毕业，被评为优秀毕业生。"

[[news]]
date = "2023-09"
content = "我将开始在东北师范大学攻读计算机科学硕士学位。"

[[news]]
date = "2023-06"
content = "我前往中国科学院计算技术研究所作为访问学生。"

[[news]]
date = "2022-03"
content = "我开始建立博客来记录我的想法。"
